In [18]:
import numpy as np
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor

In [19]:
x,y=make_classification(n_classes=2)

In [20]:
y=np.where(y==0,-1,1)

In [21]:
class ADABOST:
    def __init__(self,estimators):
        self.estimators=estimators
        self.models=[]
        self.w=[]
        
    def fit(self, x, y):
        
        self.weights = np.full(x.shape[0], 1 / x.shape[0])
        for i in range(self.estimators):
            model = DecisionTreeClassifier(max_depth=1)
            model.fit(x, y, sample_weight=self.weights)
            self.models.append(model)
            prediction = model.predict(x)
            errors = np.sum(self.weights[prediction != y])
            amount_of_say = np.log((1 - errors) / errors)
            self.weights *= np.exp(-amount_of_say * y * prediction)
            self.weights /= np.sum(self.weights)
            self.w.append(amount_of_say)
            
    def predict(self,x):
        predictions=np.zeros(x.shape[0])
        for i in range(x.shape[0]):
            pred=0
            for model,weight in zip(self.models,self.w):
                pred+=weight*model.predict([x[i]])
                
            predictions[i]=np.sign(pred)
                
            
        return predictions

In [22]:
model=ADABOST(20)

In [23]:
model.fit(x,y)

In [24]:
model.predict(x)

array([ 1., -1.,  1., -1.,  1.,  1., -1., -1., -1., -1., -1., -1., -1.,
        1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,
        1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1., -1., -1., -1., -1.,
        1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1., -1., -1., -1.,  1.,
        1., -1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1., -1., -1., -1.,
        1.,  1., -1.,  1.,  1.,  1., -1., -1., -1.,  1., -1., -1., -1.,
        1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1.,  1., -1.,
        1.,  1., -1.,  1.,  1.,  1., -1., -1.,  1.])

In [25]:
y

array([ 1, -1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1, -1,
       -1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,  1,
        1, -1, -1, -1, -1,  1,  1,  1, -1, -1,  1,  1, -1,  1, -1, -1, -1,
        1,  1, -1,  1, -1, -1,  1,  1, -1,  1,  1, -1, -1, -1,  1,  1, -1,
        1,  1,  1, -1, -1, -1,  1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1,
        1,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1])

In [16]:
from sklearn.datasets import make_regression

In [95]:
x,y=make_regression()

In [170]:
class Gradientboost:
    def __init__(self,estimators):
        self.estimators=estimators
        self.models=[]
        
        
    def fit(self,x,y):
        self.y=y
        y_pred=np.full(x.shape[0],np.mean(self.y))
        for i in range(80):
            residuals=self.y-y_pred
            model=DecisionTreeRegressor(max_depth=1)
            model.fit(x,residuals)
            self.models.append(model)
            y_pred=y_pred+0.1*model.predict(x)
            
            
    def predict(self,x):
        predictions=np.full(x.shape[0],np.mean(self.y))
        for i in range(80):
            predictions+=0.1*self.models[i].predict(x)
        
        return predictions
          

In [171]:
model=Gradientboost(20)

In [172]:
model.fit(x,y)

In [173]:
model.predict(x)

array([ 100.24663922,   86.18169712, -209.47826036,  -52.20280871,
       -189.19223437,   15.42224367,  -45.57198918, -141.12547242,
        156.15054147,  142.99917311,  -81.18817055,  -60.29743778,
        166.05524944,  147.02161004,  165.44078116, -106.2564215 ,
         31.70237189,   23.3688602 ,   79.09166441,  -55.10322533,
        -73.81803526, -201.97411227,  110.96815189, -139.13942424,
        -63.17941729, -100.66001056,   37.67181929,  136.79283472,
        368.95935978,  -72.75381804,   53.37735979, -234.31465448,
        -48.32098846, -233.90430712,  -48.67172612,  141.77954992,
        184.50845433,   32.73576798,  -79.35506928,  -93.8925766 ,
         87.52162394,  112.27757428,   64.26620995,  451.93593064,
       -173.94814526,   99.31446601,   19.49713121,  -87.76298565,
        -18.6554521 , -185.83586491,  -77.82746504,  -97.92357184,
         25.34831095, -118.74039565,   48.62123894, -198.73461629,
       -140.33698782,  196.5752681 ,  -14.2791475 , -278.12154

In [174]:
y

array([  95.92496288,  144.45479494, -261.79666287, -102.53804162,
       -288.17001073,  -32.93011129,  -81.2574411 , -217.18867988,
        191.36941333,  216.44764456,  -93.3343463 ,  -57.86840233,
        195.90415298,  283.01881763,  191.15002344,  -90.81355968,
         37.40526865,  115.90949765,  226.85327868, -165.82523247,
        -74.98303374, -320.68069486,  172.93946595, -110.42406633,
        -33.37637618, -207.81276678,   90.12448234,  160.48226123,
        478.76446054,  -83.08323182,   59.14581459, -342.11734063,
         -8.42174728, -315.47827349, -171.94579186,  258.41303691,
        287.40300793,   12.63585773,  -74.33260211,  -95.9443127 ,
        -52.61530116,  207.28655251,  151.50076792,  573.94573691,
       -234.46275505,  230.33223112,    6.15385814, -147.35313132,
          2.03428936, -301.66770866,  -73.3035155 ,  -59.11629588,
         -2.72263438, -116.4839147 ,  158.00480257, -372.81591716,
       -120.40786923,  296.49861063,  -80.74035029, -361.85588